power = read.table("household_power_consumption.txt", header=TRUE, sep = ";")
power$Date <- as.Date(power$Date, "%d/%m/%Y")
sub<-power[power$Date=="2007-02-01" | power$Date=="2007-02-02",]
sub$Global_active_power<-as.numeric(as.vector(sub$Global_active_power))
sub$Global_reactive_power<-as.numeric(as.vector(sub$Global_reactive_power))
sub$Sub_metering_1<-as.numeric(as.vector(sub$Sub_metering_1))
sub$Sub_metering_2<-as.numeric(as.vector(sub$Sub_metering_2))
sub$Sub_metering_3<-as.numeric(as.vector(sub$Sub_metering_3))
sub$Voltage<-as.numeric(as.vector(sub$Voltage))
time_date<-as.POSIXct(paste(sub$Date, sub$Time), format="%Y-%m-%d %H:%M:%S")
png("plot4.png", width = 480, height = 480, units = "px")
par(mfcol=c(2,2))
plot(time_date, sub$Global_active_power, type='l', ylab="Global Active Power", xlab="")
plot(time_date, sub$Sub_metering_1, type='l', ylab="Energy sub metering", xlab="")
lines(time_date, sub$Sub_metering_3, type='l', col='blue')
lines(time_date, sub$Sub_metering_2, type='l', col='red')
legend("topright", legend=c('Sub_metering_1','Sub_metering_2', 'Sub_metering_3'),lty=1 , col = c("black", "red","blue"))
plot(time_date, sub$Voltage, type='l', ylab="Voltage", xlab="datetime")
plot(time_date, sub$Global_reactive_power, type='l', ylab="Global_reactive_power", xlab="datetime")
dev.off()